### ISSUE TITLE
Tasks Assigning

### ISSUE THREAD

**Issue by aeh1707** [aeh1707/microverse-capstone-module-2#53]
GitHub Project: [Link](https://github.com/aeh1707/microverse-capstone-module-2/projects/1)
N. of Collabortarors: Two ( @aeh1707 and @Kirabo19 )

**Comment by mateo951** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aeh1707** [comment]
Thanks @mateo951
